CREATE OR REPLACE PROCEDURE BRONZE.DWH_LOAD_CRM_ERP_BRONZE()
RETURNS STRING
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
BEGIN

    -- CRM CUSTOMER INFO
    TRUNCATE TABLE BRONZE.CRM_CUST_INFO;
    COPY INTO BRONZE.CRM_CUST_INFO
    FROM @BRONZE.GCS_CRM_ERP_STAGE/cust_info.csv
    ON_ERROR = 'CONTINUE';

    -- CRM PRODUCT INFO
    TRUNCATE TABLE BRONZE.CRM_PRD_INFO;
    COPY INTO BRONZE.CRM_PRD_INFO
    FROM @BRONZE.GCS_CRM_ERP_STAGE/prd_info.csv
    ON_ERROR = 'CONTINUE';

    -- CRM SALES DETAILS
    TRUNCATE TABLE BRONZE.CRM_SALES_DETAILS;
    COPY INTO BRONZE.CRM_SALES_DETAILS
    FROM @BRONZE.GCS_CRM_ERP_STAGE/sales_details.csv
    ON_ERROR = 'CONTINUE';

    -- ERP LOC A101
    TRUNCATE TABLE BRONZE.ERP_LOC_A101;
    COPY INTO BRONZE.ERP_LOC_A101
    FROM @BRONZE.GCS_CRM_ERP_STAGE/LOC_A101.csv
    ON_ERROR = 'CONTINUE';

    -- ERP PX CAT G1V2
    TRUNCATE TABLE BRONZE.ERP_PX_CAT_G1V2;
    COPY INTO BRONZE.ERP_PX_CAT_G1V2
    FROM @BRONZE.GCS_CRM_ERP_STAGE/PX_CAT_G1V2.csv
    ON_ERROR = 'CONTINUE';

    -- ERP CUSTOMER AZ12
    TRUNCATE TABLE BRONZE.ERP_CUST_AZ12;
    COPY INTO BRONZE.ERP_CUST_AZ12
    FROM @BRONZE.GCS_CRM_ERP_STAGE/CUST_AZ12.csv
    ON_ERROR = 'CONTINUE';

    RETURN 'BRONZE LOAD FROM AWS COMPLETED SUCCESSFULLY';

END;
$$;