

CREATE OR REPLACE FILE FORMAT CSV_PIPE_FILEFORMAT
TYPE = CSV
FIELD_DELIMITER = ','
SKIP_HEADER = 0
NULL_IF = ('NULL','Null','null') 
FIELD_OPTIONALLY_ENCLOSED_BY = '"'        
EMPTY_FIELD_AS_NULL = TRUE;


CREATE OR REPLACE STORAGE INTEGRATION AWS_S3_INT
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = S3
ENABLED = TRUE 
STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::149901571476:role/snowflake_project'
STORAGE_ALLOWED_LOCATIONS = ('s3://mln-snowflake')
COMMENT = 'Create Storage integration to connect Snowflake with AWS' ;

DESCRIBE INTEGRATION AWS_S3_INT;


CREATE OR REPLACE STAGE BRONZE.GCS_CRM_ERP_STAGE
STORAGE_INTEGRATION = AWS_S3_INT
URL = 's3://mln-snowflake/'
FILE_FORMAT = CSV_PIPE_FILEFORMAT;


list @BRONZE.GCS_CRM_ERP_STAGE;

