


CREATE OR REPLACE TASK BRONZE.TASK_DWH_LOAD_CRM_ERP_BRONZE
WAREHOUSE = COMPUTE_WH
SCHEDULE = 'USING CRON 0 2 * * * Asia/Kolkata'
AS
CALL BRONZE.DWH_LOAD_CRM_ERP_BRONZE();




CREATE OR REPLACE TASK BRONZE.TASK_SILVER_LOAD
WAREHOUSE = COMPUTE_WH
AFTER BRONZE.TASK_DWH_LOAD_CRM_ERP_BRONZE
AS
CALL silver.load_silver()();



CREATE OR REPLACE TASK BRONZE.load_gold_proc
WAREHOUSE = COMPUTE_WH
AFTER BRONZE.TASK_SILVER_LOAD
AS
CALL gold.load_gold();


ALTER TASK BRONZE.TASK_GOLD_LOAD RESUME;
ALTER TASK BRONZE.TASK_SILVER_LOAD RESUME;
ALTER TASK BRONZE.TASK_DWH_LOAD_CRM_ERP_BRONZE RESUME;

SHOW TASKS;